name: Continuous Integration

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  lint:
    name: project lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: |
          npm run eslint
          npm run prettier